export enum MapInputType {
  Skills = 'skills',
  TimeWindowStart = 'time_window_start',
  TimeWindowEnd = 'time_window_end',
  SingleTimeWindowStart = 's_time_window_start',
  SingleTimeWindowEnd = 's_time_window_end',
  LocationLngLat = 'LocationLngLat',
  LocationLatLng = 'LocationLatLng',
  LocationLat = 'location_lat',
  LocationLng = 'location_lng',
  Number = 'number',
  Capacity = 'capacity',
  Start_Depot_IDs = 'start_depot_ids',
  Depot_IDs = 'depot_ids',
  End_Depot_IDs = 'end_depot_ids',
  Amount = 'amount',
  PickupCapacity = 'pickupCapacity',
  DeliveryCapacity = 'deliveryCapacity',
  Description = 'description',
  Float = 'float',
  Array = 'array',
  // New field types
  Boolean = 'boolean',
  VolumeAlignment = 'volume_alignment',
  LoadTypes = 'load_types',
  IncompatibleLoadTypes = 'incompatible_load_types',
  Metadata = 'metadata',
  Revenue = 'revenue',
  OutsourcingCost = 'outsourcing_cost',
  MaxVisitLateness = 'max_visit_lateness',
  SequenceOrder = 'sequence_order',
  MaxTimeInVehicle = 'max_time_in_vehicle',
  JointOrder = 'joint_order',
  Zones = 'zones',
}

// Define the VehicleMapOption enum
export enum VehicleMapOption {
  ID = 'id',
  Description = 'description',
  MaxTasks = 'max_tasks',
  Skills = 'skills',
  StartLocationLngLat = 'start_location#lngLat',
  StartLocationLatLng = 'start_location#latLng',
  StartLocationLat = 'start_location#lat',
  StartLocationLng = 'start_location#lng',
  EndLocationLngLat = 'end_location#lngLat',
  EndLocationLatLng = 'end_location#latLng',
  EndLocationLat = 'end_location#lat',
  EndLocationLng = 'end_location#lng',
  StartTime = 'start_time',
  EndTime = 'end_time',
  DepotID = 'depot',
  StartDepotIDs = 'start_depot_ids',
  StartDepotID1 = 'Start Depot ID 1',
  EndDepotIDs = 'end_depot_ids',
  EndDepotID1 = 'End Depot ID 1',
  Capacities = 'capacity',
  Capacity1 = 'capacity 1',
  Capacity2 = 'capacity 2',
  Capacity3 = 'capacity 3',
  SpeedFactor = 'speed_factor',
  FixedCost = 'costs.fixed',
  CostPerHour = 'costs.per_hour',
  CostPerKm = 'costs.per_km',
  MaxTravelCost = 'max_travel_cost',
}

// Define the JobMapOption enum
export enum JobMapOption {
  ID = 'id',
  Description = 'description',
  Address = 'address',
  LocationLatLng = 'location#latLng',
  LocationLngLat = 'location#lngLat',
  LocationLat = 'location#lat',
  LocationLng = 'location#lng',
  ServiceTime = 'service',
  Skills = 'skills',
  StartTime = 'time_windows_start',
  EndTime = 'time_windows_end',
  DepotIDs = 'depot_ids',
  DepotID1 = 'Depot ID 1',
  Priority = 'priority',
  Setup = 'setup',
  PickupCapacities = 'pickup',
  PickupCapacity1 = 'pickup capacity 1',
  PickupCapacity2 = 'pickup capacity 2',
  PickupCapacity3 = 'pickup capacity 3',
  DeliveryCapacities = 'delivery',
  DeliveryCapacity1 = 'delivery capacity 1',
  DeliveryCapacity2 = 'delivery capacity 2',
  DeliveryCapacity3 = 'delivery capacity 3',
  // New fields from OpenAPI spec
  Revenue = 'revenue',
  OutsourcingCost = 'outsourcing_cost',
  LoadTypes = 'load_types',
  IncompatibleLoadTypes = 'incompatible_load_types',
  SequenceOrder = 'sequence_order',
  FollowLifoOrder = 'follow_lifo_order',
  MaxVisitLateness = 'max_visit_lateness',
  VolumeWidth = 'volume.width',
  VolumeDepth = 'volume.depth',
  VolumeHeight = 'volume.height',
  VolumeAlignment = 'volume.alignment',
  JointOrder = 'joint_order',
  Zones = 'zones',
  ZoneID = 'zone_id',
  // Metadata fields
  MetadataContact = 'metadata.contact',
  MetadataNotes = 'metadata.notes',
  MetadataMetaId = 'metadata.metaId',
}

// Define the ShipmentMapOption enum
export enum ShipmentMapOption {
  Description = 'description',
  Address = 'address',
  Skills = 'skills',
  Priority = 'priority',
  Setup = 'setup',
  PickupID = 'pickup.id',
  PickupService = 'pickup.service',
  PickupPriority = 'pickup.priority',
  PickupLocationLatLng = 'pickup.location#latLng',
  PickupLocationLngLat = 'pickup.location#lngLat',
  PickupLocationLat = 'pickup.location#lat',
  PickupLocationLng = 'pickup.location#lng',
  PickupStartTime = 'pickup.time_windows_start',
  PickupSetup = 'pickup.setup',
  PickupEndTime = 'pickup.time_windows_end',
  PickupMaxVisitLateness = 'pickup.max_visit_lateness',
  PickupSequenceOrder = 'pickup.sequence_order',
  PickupMetadataContact = 'pickup.metadata.contact',
  PickupMetadataNotes = 'pickup.metadata.notes',
  PickupMetadataMetaId = 'pickup.metadata.metaId',
  DeliveryID = 'delivery.id',
  DeliveryService = 'delivery.service',
  DeliveryPriority = 'delivery.priority',
  DeliveryLocationLatLng = 'delivery.location#latLng',
  DeliveryLocationLngLat = 'delivery.location#lngLat',
  DeliveryLocationLat = 'delivery.location#lat',
  DeliveryLocationLng = 'delivery.location#lng',
  DeliveryStartTime = 'delivery.time_windows_start',
  DeliveryEndTime = 'delivery.time_windows_end',
  DeliverySetup = 'delivery.setup',
  DeliveryMaxVisitLateness = 'delivery.max_visit_lateness',
  DeliverySequenceOrder = 'delivery.sequence_order',
  DeliveryMetadataContact = 'delivery.metadata.contact',
  DeliveryMetadataNotes = 'delivery.metadata.notes',
  DeliveryMetadataMetaId = 'delivery.metadata.metaId',
  AmountCapacities = 'amount',
  AmountCapacity1 = 'amount capacity 1',
  AmountCapacity2 = 'amount capacity 2',
  AmountCapacity3 = 'amount capacity 3',
  // New fields from OpenAPI spec
  Revenue = 'revenue',
  OutsourcingCost = 'outsourcing_cost',
  LoadTypes = 'load_types',
  IncompatibleLoadTypes = 'incompatible_load_types',
  MaxTimeInVehicle = 'max_time_in_vehicle',
  FollowLifoOrder = 'follow_lifo_order',
  VolumeWidth = 'volume.width',
  VolumeDepth = 'volume.depth',
  VolumeHeight = 'volume.height',
  VolumeAlignment = 'volume.alignment',
  JointOrder = 'joint_order',
  Zones = 'zones',
  ZoneID = 'zone_id',
} 